# Generated by Django 4.2.5 on 2023-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='service_charge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
