# Generated by Django 4.2.5 on 2023-10-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_gender_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
