# Generated by Django 4.2.5 on 2023-11-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason_for_visit',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
