# Generated by Django 4.2.5 on 2023-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_appointment_reason_for_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Accept', 'Accept')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
